### ISSUE TITLE
conflict with markdown???

### ISSUE THREAD

**Issue by EdchaSw** [tintinweb/vscode-inline-bookmarks#17]
Hello, thank you very much for this excellent extension, I have been using it for a while.

But recently I installed extensions for markdown and a note like Unotes, and since then many features were disabled, it is no longer automatically updated in the code and the assigned color is not seen.

Do you know of any conflict with Markdown?

**Comment by tintinweb** [comment]
Hey @EdchaSw, 

that's weird, there shouldn't be any conflicts with other extensions. Did you see any errors popping up? Do you see any errors when you `toggle developer tools`?

As a last resort, I've recently added a command that resets the extensions configuration in case the workspace is all messed up. You should not have to use it and in that case it is a bug we need to fix but you might want to try to reset it. Note: your bookmarks will temporarily be cleared from the view on the left side and they will be populated as you open files with bookmarks again.

![image](https://user-images.githubusercontent.com/2865694/83787539-3ef78180-a694-11ea-98f5-914a7eb598de.png)

**Comment by EdchaSw** [comment]
Hi @tintinweb ,

thanks to respond

this is a sample of the problem, please look the image
The @todo is not highlighted as before and it no longer recognizes bookmarks

![image](https://user-images.githubusercontent.com/6707274/83893148-d26c9900-a70c-11ea-9d98-b36135518512.png)

and this my setting

![image](https://user-images.githubusercontent.com/6707274/83893263-f8923900-a70c-11ea-9f4b-0a62a2327cc6.png)
![image](https://user-images.githubusercontent.com/6707274/83893342-1069bd00-a70d-11ea-9779-e0f51cfc022a.png)
![image](https://user-images.githubusercontent.com/6707274/83893389-1c557f00-a70d-11ea-9c8d-e51efbaa14d5.png)

I hope you can help me, this Extension is very good and I would not like to lose it

**Comment by tintinweb** [comment]
Hi @EdchaSw thanks for providing more information.

I just fixed a bug that caused the extension to exit too early when registering. This can be caused by a couple of events (e.g. bad timing, other extensions being visible first, or if no editor was open).

I've attached a development build and would kindly ask you to test it and provide feedback if this resolves the issue for you.

Here's the vsix file: `MD5 (vscode-inline-bookmarks-0.0.18.vsix.png) = afb24f22c45c68ea1186276df52f910d`

* download [vscode-inline-bookmarks-0 0 18 vsix.png](https://user-images.githubusercontent.com/2865694/83948765-e81eb300-a81f-11ea-88d4-b66880801e21.png)
* rename to .vsix
* `code --install-extension vscode-inline-bookmarks-0.0.18.vsix`

Sidenote: you seem to be using old patterns for the tags that require a whitespace at the end. You may want to reset these patterns to the defaults or adjust them to include `$` as seen in the screenshot:

![image](https://user-images.githubusercontent.com/2865694/83948432-77769700-a81d-11ea-8859-3235ff092d35.png)

let me know if that works for you.

cheers & thanks for reporting,

tin

**Comment by EdchaSw** [comment]
Hi @tintinweb 


Thanks to help me, 

You tell me

> I've attached a development build and would kindly ask you to test it and provide feedback if this resolves the issue for you.
> 
> Here's the vsix file: MD5 (vscode-inline-bookmarks-0.0.18.vsix.png) = afb24f22c45c68ea1186276df52f910d
> 
>     download vscode-inline-bookmarks-0 0 18 vsix.png
>     rename to .vsix
>     code --install-extension vscode-inline-bookmarks-0.0.18.vsix

But I click in your link and nothing to download me

How I can download your development build?

Thanks.

Edchasw

**Comment by tintinweb** [comment]
@EdchaSw right click -> save link as. otherwise your browser might try to interpret it as a `png`. Had to rename it in order to be able to share it directly on github with you.

**Comment by tintinweb** [comment]
@EdchaSw did that resolve the issue?

**Comment by tintinweb** [comment]
published as https://github.com/tintinweb/vscode-inline-bookmarks/releases/tag/v0.0.18

**Comment by EdchaSw** [comment]
> 
> 
> @EdchaSw did that resolve the issue?

Hi @tintinweb  I am sorry I did not answer you, I have been entangled in several issues, this morning I have updated to the version you just left 0.0.18, and the problem was solved in full, I thank you for your kind attention and help, thank you very much for the update

Atte

Edchasw
