### ISSUE TITLE
inline-bookmarks within workspace-cache cannot be removed

### ISSUE THREAD

**Issue by smallscript** [tintinweb/vscode-inline-bookmarks#45]
Kudos,
Very nice tool, thank you for the work.

Issue
AFAIK inline-bookmarks is using the workspace-cache to retain bookmarks pojo. Therefore when switching workspace/projects there is no option to reset/filter to the active workspace. I.e., it seems to forever retain all bookmarks as long as their file exists even if they are not part of the workspace.

This may be intentional. However, if so, then something like "refresh" or "find" should provide some way to CLEAR stale bookmarks to EXISTING files which are NOT within the workspace projects unioned with any open-editors.

**Comment by smallscript** [comment]
p.s., I have verified this and within my VsCode I patched the refresh-workspace command to begin with
```javascript
this.controller.bookmarks = {};
```
which properly/adequately allows manual cache flushing whenever the magnifying-glass icon is clicked.

**Comment by tintinweb** [comment]
Hey @smallscript,

did you try this command? This should clear the workspace cache

![image](https://user-images.githubusercontent.com/2865694/143856044-e766ea16-4bab-4a3f-9a47-25ffd28f0a6b.png)

**Comment by tintinweb** [comment]
some more information:

we're caching bookmarks in the workspace context. This means, if you switch workspaces you're using another cache specific to that workspace. There shouldn't be any files from the previous workspace. This, however, might be more complex if you're using a multi-workspace setting or if you are removing files outside of vscode. Currently, when refreshing, we do not check if the files still exist on disk (note that some files might just be in memory and not even exist on disk). For files outside your workspace you might still want them to show up in the view (because e.g. they're in an active editor window). Resetting the cache at this point would remove these bookmarks. 

Looks like fixing this might be a little more complex. Would be great to get more input on how users want this to work 🤔
